
from azure.storage.blob import BlobClient

# Replace with your SAS URL generated by your GetSasToken function
sas_url = "https://athleticstorage.blob.core.windows.net/uploads/test21.mp4?sv=2025-01-05\u0026st=2025-01-21T12%3A02%3A20Z\u0026se=2025-01-21T12%3A32%3A20Z\u0026sr=b\u0026sp=rw\u0026sig=aQoWgdFbZriMAHYsUP%2BpwqnXdLYr80r4YSF2Bjwp8Rw%3D"

# Local video file path you want to upload
video_file_path = "/Users/cezar/Desktop/TeamProject/orig.mp4"

# Create a BlobClient from the SAS URL
blob_client = BlobClient.from_blob_url(sas_url)

# Open the local video file in binary mode and upload it
with open(video_file_path, "rb") as data:
    blob_client.upload_blob(data, overwrite=True)

print("Upload successful!")


